package questao04.Enums;

public enum Categoria {CELULARES_E_TELEFONES, INFORMATICA, TV_E_ELETRONICOS, ELETRODOMESTICOS, ELETROPORTATEIS,
    MODA_E_ACESSORIOS, MOVEIS_E_DECORACAO, ESPORTE_E_LAZER, GAMES, OUTRAS_CATEGORIAS;}
